### ISSUE TITLE
Full auth implementation

### ISSUE THREAD

**Issue by cnp0** [cnp0/repomint#22]
See #10 for remaining work.

**Comment by idiglove** [comment]
What I've done so far (Sept 19, 2021)
- [ ] Oauth using Github Web App Flow
- [ ] login with octokit and get user's info

Things missing:
- [ ] persist user's github session through reloads, etc

**Comment by cnp0** [comment]
This is awesome :confetti_ball:. Is there a reason this is in the *solana_mint* folder? dont we want this in *src*? I'd imagine eventually the react app would be in something like a *web* folder. Maybe I'm missing something though.

**Comment by idiglove** [comment]
Yea solana_mint is meant to be a nodejs backend server, i'll rename it, sorry for confusion 😅

**Comment by cnp0** [comment]
Ah got it! my b

**Comment by cnp0** [comment]
I can throw out *gatekeeper* right?

**Comment by idiglove** [comment]
> I can throw out _gatekeeper_ right?

yep we can

**Comment by cnp0** [comment]
Hey do we intend to set 

```bash
export OCTOKIT_GITHUB_OAUTH_CLIENT_ID=
export OCTOKIT_GITHUB_OAUTH_CLIENT_SECRET=
```

manually? before using the `REACT_APP_*` prefix allowed react to load environment variables automagically. It's find it we dont. I'll add the documentation for now.

**Comment by cnp0** [comment]
Also, im not too familiar with this stuff, but should the auth token be stored in a cookie? i feel like thats kinda dangerous.

**Comment by idiglove** [comment]
> Also, im not too familiar with this stuff, but should the auth token be stored in a cookie? i feel like thats kinda dangerous.

Yes its fine, we can make it more secure by making it httpOnly https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
but we would need our site to be ssl and have it https
